# my_file2 = open("people1.txt", "w")
# my_file2.write("Abhishek - Gurgaon")
# my_file2.write("Ranveer - Delhi")
# print ("AbhishekRanveer")
# print ("---------------------------------")
# print ("Abhishek\nRanveer")
# print ("---------------------------------")
# print ("Abhishek\n\nRanveer")
# print ("---------------------------------")
# my_file2.close()


my_file2= open("people2.txt", "w")
my_file2.write("Abhishek - Gurgaon\n")
my_file2.write("Ranveer - Delhi")
my_file2.close()